import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Montserrat } from "@next/font/google";
import { NextFont } from "@next/font";

export const metadata: Metadata = {
	title: "Pops Barbershop",
	description: "Generated by create next app"
};

const montserrat: NextFont = Montserrat({
	subsets: ["latin"]
});

export default async function RootLayout({
	children,
	params: { locale }
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<head>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>Pops barbershop</title>
			</head>
			<body className={montserrat.className}>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<main>{children}</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
